### ISSUE TITLE
set license when publishing to hex

### ISSUE THREAD

**Issue by mirceal** [elixir-lang/gettext#121]
https://hex.pm/packages/gettext

Currently it does not show any license. You have to dig through the repo to figure out it's Apache 2.0
it would be helpful if one could learn this by looking at hex.pm directly

**Comment by whatyouhide** [comment]
Hey @mirceal, If I go to https://hex.pm/packages/gettext I see the "License" section where it says "Apache 2.0", as confirmed by [this line in `mix.exs`](https://github.com/elixir-lang/gettext/blob/bd5d3a2c0307fd346bf1043bea294e87496491d8/mix.exs#L33) where that license is set. 😕

I'm gonna close this for now, but feel free to reopen this if you still can't see any license, maybe with attached screenshot and more details. :)
