### ISSUE TITLE
"mix test --stale" doesn't work with Gettext

### ISSUE THREAD

**Issue by whatyouhide** [elixir-lang/gettext#123]
I have to investigate why. It basically just runs as `mix test` without caching tests or even printing anything that `mix test --stale` usually prints. @antipax if you have any quick idea on why this could be, feel free to chime in :)

**Comment by josevalim** [comment]
Just to be double sure, you are on latest Elixir right? :)

-- 


*José Valim*
www.plataformatec.com.br
Skype: jv.ptec
Founder and Director of R&D

**Comment by whatyouhide** [comment]
I tend to always run Elixir master but I hadn't pulled in a couple days, anyways just pulled the latest master and this still happens.
<img width="515" alt="screen shot 2016-09-19 at 14 18 37" src="https://cloud.githubusercontent.com/assets/3890250/18631732/fe2f783e-7e73-11e6-9ef2-631ed3f3c17b.png">

**Comment by josevalim** [comment]
and possibility is that the gettext tests are touching a source file or something similar and that's always busting the stale cache.

**Comment by whatyouhide** [comment]
That would be my bet, yes. I haven't investigated this even a second :), but I will investigate as soon as I can.

**Comment by antipax** [comment]
@josevalim is probably right. 

I'm going to take a look at this as well, will let you two know if I find anything. :)
