### ISSUE TITLE
Extract dynamic translation calls

### ISSUE THREAD

**Issue by schurig** [elixir-lang/gettext#125]
We wrote a [hex package](https://github.com/sbrink/phoenix_simple_form) for phoenix that makes form handling easier.

Unfortunately, we didn't find any way to use the `mix gettext.extract` with it.

## Example
`%User{first_name: "....", last_name: "....."}` (User model)

`<%= input f, :first_name %>` (User form)

**It calles:**

```elixir
Gettext.dgettext(MyApp.Gettext, "forms", "user.first_name.label")
```
_[(source code)](https://github.com/sbrink/phoenix_simple_form/blob/master/lib/phoenix_simple_form/style_helpers.ex#L24-L31)_

____

Is there any way to automatically extract these translation-keys?

**Comment by josevalim** [comment]
No. Dynamic translations need to be added by hand.

**Comment by josevalim** [comment]
Btw, this week we are publishing a blog post on @plataformatec's blog on why we are not writing something like SimpleForm for Phoenix. We show it is straight-forward to implement it in your application, without having to dig through many configurations and options, which is what ended-up happening with most of our SimpleForm projects. Anyway, I thought you would appreciate the heads up. :D
