### ISSUE TITLE
Running mix gettext.extract in umbrella updates wrong app

### ISSUE THREAD

**Issue by wojtekmach** [elixir-lang/gettext#126]
Hi, I'm moving our project that uses gettext into an umbrella and I noticed that running `mix gettext.extract` from umbrella root updates the wrong app.

In a sample app, I install gettext in app `foo`, but extracting from the umbrella root adds files to the `bar` app: https://github.com/wojtekmach/gettext_umbrella/commit/f43292c2c014ab86b327b369576d03c91091809a. When I first run `cd apps/foo && mix gettext.extract` it does the correct thing, and then running extract again from root does nothing which is good too.

Btw, are there any recommendations for using gettext in an umbrella? E.g.:

1. a single `MyProject.Gettext` module that some apps depend on, and a single `priv/gettext` directory.
2. `Foo.Gettext`, `Bar.Gettext` etc, each with it's own `priv/gettext` (need to remember to call `Gettext.put_locale(Foo.Gettext, locale) && Gettext.put_locale(Bar.Gettext, locale)` in function that changes locale for the app though)
3. It depends :-)

Thanks!

**Comment by whatyouhide** [comment]
Hey @wojtekmach,

I have to confess that I never used Gettext and umbrella apps together. One idea to solve this can be to have a Gettext-responsible **app** instead of module leaving in an app (for example, `apps/my_project_translations` or something like this). I honestly have no idea how this will behave with `gettext.extract` though.

I don't know why this happens anyways, `gettext.extract` is marked as a recursive task so it should just run in every app of the umbrella project and not mess from app to app. @josevalim any ideas?

I won't have time to look into this for a few days, so @wojtekmach if you feel like investigating you're more than welcome, I can try and help anytime I can. :)

**Comment by josevalim** [comment]
Here is what it happens:

```
Generated gettext app
[setup: :bar]
[force_compile: :bar]
==> bar
Compiling 1 file (.ex)
Generated bar app
==> foo
Compiling 2 files (.ex)
Generated foo app
[pot_files: :bar]
[setup: :foo]
[force_compile: :foo]
[pot_files: :foo]
```

So I think the solution is that we need to "key" the translations inside the extractor. We could pass an anonymous function to setup that tells it how to retrieve the current app:

    Gettext.Extractor.setup(fn -> Mix.Project.config[:app] end)

And when getting the pot files, we get for that particular project:

    Gettext.Extractor.pot_files(Mix.Project.config[:app])

**Comment by josevalim** [comment]
I have pushed a fix. However, before merging it, we need to discuss what should happen here: https://github.com/elixir-lang/gettext/commit/3effec2ae176d0644059dd4ea578c2ff17c089ed#diff-56d4faf828fa99ba6ebb2d82b745d2fdR29

Given we now pop the translations, maybe we should the extractor agent permanently? /cc @whatyouhide

**Comment by whatyouhide** [comment]
@josevalim I'll try and give a look tonight :)

**Comment by whatyouhide** [comment]
@josevalim as I understand, the extractor now keeps all the translations across the compilation so I guess that yes, not starting/stopping together with `gettext.extract` would be the correct solution.

So when we run recursive Mix tasks it all happens in the same run? It makes sense but I always imagined it as shutting down the VM after the task execution in each app and starting a new for execution in the next app, which doesn't really make sense and I think I just never stopped to think about it 😄

So then yes, your solution looks ok to me. Shall we proceed?

**Comment by wojtekmach** [comment]
@josevalim @whatyouhide thank you so much for a quick fix for this, I was able to verify it works well for both setups:
- [separate Foo.Gettext and Bar.Gettext](https://github.com/wojtekmach/gettext_umbrella)
- [single Translator.Gettext](https://github.com/wojtekmach/gettext_umbrella/tree/translator)

thanks again! :+1:

**Comment by jstlroot** [comment]
@wojtekmach I would love to see how you implemented a single Translator.Gettext as I am unable to extract translations from many apps to a single translator app in an umbrella.

Your `single Translator.Gettext` link is broken.

Cheers!

**Comment by wojtekmach** [comment]
Hey, here’s how I approached it:
- create apps/translator which stored all translation .po files
- add `{:translator, in_umbrella: true}` dep in each app that needed it
- add `compilers: [:gettext | Mix.compilers()]` in each app that needed it

Then, run `mix gettext.extract` etc from umbrella root.

Hope it helps!

**Comment by jstlroot** [comment]
Thank you, it works!

I then ran into this issue: https://github.com/elixir-lang/gettext/issues/178 but @amatalai 's idea worked well: https://gist.github.com/amatalai/1877f48a195f578682cfd20e66c6544e

Cheers!
