### ISSUE TITLE
Gettext.with_locale/5 with mfa

### ISSUE THREAD

**Issue by whatyouhide** [elixir-lang/gettext#139]
Today, we have `Gettext.with_locale/3` that takes a backend, a locale, and an anonymous function. I was wondering if it could be beneficial to have `Gettext.with_locale/4` that takes a backend, a locale, and a mfa:

```elixir
Gettext.with_locale(MyApp.Gettext, "en", MyModule, :my_fun, [arg1, arg2])
```

It could reduce the overhead of the closure of the anonymous function, but maybe we could wait for real-world use cases. Anyways, I thought discussing this briefly could be good :)

\cc @lexmag @josevalim

**Comment by josevalim** [comment]
The overhead is negligible.

**Comment by whatyouhide** [comment]
Ok, then we shall wait for someone who actually has use cases for this :). Thanks for the feedback @josevalim!
