### ISSUE TITLE
Message context should be parsed, even when ignored.

### ISSUE THREAD

**Issue by erneestoc** [elixir-lang/gettext#142]
I'm using an online localization tool to translate my application, and msgctxt is causing my build to fail. 

I think we should at least parse and ignore msgctxt so that we can use any tool to translate our apps.

I'm using..
https://poeditor.com

**Comment by whatyouhide** [comment]
That sounds reasonable, we should not fail for external PO files as we should support the PO format in its entirety.

**Comment by whatyouhide** [comment]
Hey @erneestoc, this was implemented in #143. Could you give master a try and let us know how it works? :)
