### ISSUE TITLE
Global Gettext context

### ISSUE THREAD

**Issue by OvermindDL1** [elixir-lang/gettext#147]
As per the discussion at:  https://elixirforum.com/t/gettext-in-a-hex-package/3447/6

> Maybe there should be some kind of get global instance call that everything hooks in to by default (perhaps even namespaced based on the application name)? That'd still leave a way for specific instances as well but everything by default would share a global (potentially namespaced translations) instance?

And recommended initial-thought implementation via @josevalim:

> That's a good call. We could have a Gettext.locale/0 and Gettext.locale/1 that would use gettext own's app environment and we could make all default backends use it by default. Can someone please open up an issue?

**Comment by whatyouhide** [comment]
> we could make all default backends use it by default

@josevalim do you mean that all backends should use it by default? Otherwise not sure what you mean with "default backends".

Also, would `Gettext.put_locale/1` change the default locale for all instances in different processes? Or did you mean that `put_locale/1` would still put the locale in the current pdict and then `get_locale(MyApp.Gettext)` would read it out when one for `MyApp.Gettext` is not found?

**Comment by josevalim** [comment]
> Or did you mean that put_locale/1 would still put the locale in the current pdict and then get_locale(MyApp.Gettext) would read it out when one for MyApp.Gettext is not found?

This.

**Comment by whatyouhide** [comment]
Ok, great.

I can work on this in a few days but if someone wants to give it a shot it would consist of implementing `Gettext.put_locale/1` and `Gettext.get_locale/0`, and changing `Gettext.get_locale/1` to account for this new default locale. We should store this new locale under a key like `:gettext_locale` or `:global_gettext_locale` or `:fallback_gettext_locale` or `:default_gettext_locale` in the pdict; @josevalim suggestion on the name?

**Comment by josevalim** [comment]
Couldn't we use the same structure we use for the other backends except we use `Gettext` as module name?

**Comment by whatyouhide** [comment]
Yeah I thought about that but it could look a bit mysterious in the pdict, but I guess it's fine considering we do this for all backends. 👍

**Comment by whatyouhide** [comment]
Closed in #148.
