### ISSUE TITLE
Parsing {:safe, html} as interpolations

### ISSUE THREAD

**Issue by aphillipo** [elixir-lang/gettext#157]
Sorry to ask directly on GitHub but I've asked in a few places and not had any response.

```elixir
sgettext "{link_here_html} is a link to the {strong_link_html} documentation I was discussing...",
    link_here_html: link(gettext("Here"), some_path(@conn, :index)), 
    strong_link_html: {:safe, "<strong><a href=\"/path/somewhere/\">#{gettext("some link text")}</a></strong>"}
```

So obviously I created a function to support this in the Gettext module of my phoenix project:

```elixir
  @spec sgettext(binary, map) :: binary
  def sgettext(msgid, bindings) when is_binary(msgid) and is_list(bindings) do
    # no html in keys without being escaped; translators shouldn't be allowed html
    safe_message_id = Plug.HTML.html_escape(msgid)  
    safe_bindings = Enum.map(bindings, fn({interpolate_key, interpolate_value}) ->
      case interpolate_value do
        {:safe, real_value} -> {interpolate_key, real_value}  # we assume that {:safe, iolist} is allowed.
        _ -> {interpolate_key, Plug.HTML.html_escape(interpolate_value)}
      end
    end)
    {:safe, Gettext.gettext(__MODULE__, safe_message_id, safe_bindings)}
  end
```

Clearly the extractor is never going to work with this new function, which I didn't think about before writing it.  Is there a better/correct way to do this; I'm loathe to split up individual strings into and out of html like this but I still want to avoid translations containing html as well for security reasons.

**Comment by josevalim** [comment]
Can you assume that the gettext messages are safe? If they are safe, then you can escape all of the arguments before calling gettext, converting them to string, and then assume the overall string is safe.

If gettext cannot assumed to be safe, then you will need a mechanism to retrieve the raw messages and do the interpolation yourself.

**Comment by aphillipo** [comment]
Hi @josevalim - if you look at what I do in the sgettext function I make sure the message_id is safe:

```elixir
safe_message_id = Plug.HTML.html_escape(msgid)
```

As well as any keys that are not passed as {:safe, ""}.  I can definitely do as your saying but I don't trust external services like the ones that might be translating my messages.  Always filter user input and all that.  Just because it's from a more secure source I would still prefer if these could be filtered.

**Comment by aphillipo** [comment]
Edit, actually this is still problematic because the translation could still be anything.

I'll close this and mark the whole string as safe.  Thanks!
