### ISSUE TITLE
Consider making comments in .po files configurable / optional

### ISSUE THREAD

**Issue by manukall** [elixir-lang/gettext#159]
The current behavior of adding all the occurrences as `filename:linenum` comments to the .po files leads to  huge commits every time we add just a single new translation in our app. 

Usually we've also changed our app in different places in the meantime and all the line numbers are different now, so basically every comment in every .po file is changed when runnning `mix gettext.extract --merge`.

I'd love for a way to either make the comments completely optional or configurable in a way that lets us turn off line numbers.

**Comment by whatyouhide** [comment]
We use `file:line` because that's what GNU gettext uses. Have you researched if tools (like POEdit) understand reference comments then the format for such comments is not `file:line`?

**Comment by manukall** [comment]
I have not as I wasn't aware that was an official thing. After reading https://www.gnu.org/software/gettext/manual/html_node/PO-Files.html, 

I think maybe it makes more sense to just allow turning those reference comments off. Above document states "All comments, of either kind, are optional".

**Comment by whatyouhide** [comment]
Making reference comments optional might be a viable way of solving the problem, but it does introduce a bit of complexity in how Gettext works. @josevalim thoughts?

**Comment by josevalim** [comment]
Sounds good, yes.

**Comment by whatyouhide** [comment]
@manukall are you willing to work on a PR for this? :)

**Comment by manukall** [comment]
@whatyouhide i've got a pretty full schedule for the next weeks, so anything complicated during that time isn't realistic. if that's a smaller change or if it has time until later, i'd absolutely be willing, though.

do you have an idea about the implementation, yet? i guess simply checking `Application.get_config(...)` in `Gettext.PO.dump_references/1` wouldn't be good enough, right? ;-)

**Comment by whatyouhide** [comment]
It wouldn't yeah. We moved all Gettext configuration to `mix.exs` under the `:gettext` key so we would need to store this information there and pass that around to the right places. I can work on it, no worries.

**Comment by whatyouhide** [comment]
Closing in favour of #161.
