### ISSUE TITLE
Comments tokenizing + parsing

### ISSUE THREAD

**Issue by whatyouhide** [elixir-lang/gettext#16]
Comments in Gettext are not like comments everywhere else, since you usually don't just ignore them.

Comments start with an hash (`#`) character and go on until EOL. There are two main kinds of comments:

- translator comments (denoted by `#` followed by some whitespace, most commonly `#[space]`)
- autogenerated comments (`#` followed by some specifier character)

We will need to parse, tokenize and keep **all** those comments associated with each translation since they are necessary to rebuild PO files exactly like we found them. Also, we can obviously make use of the autogenerated comments.

## Translator comments

```po
# This is a translator comment.
msgid "foo"
msgstr "bar"
```

We'll keep them as is, nice and easy.

## Autogenerate comments

```po
#. extracted-comments
#: reference
#, flag
#| msgid previous-untranslated-string
```

**Extracted comments**: they're written by the programmer, in the source code, for the translator. I think we should avoid implementing this for now as we would need some kind of macro to do this as well.

```po
#. Hey translator, thanks!
...
```

**Reference**: file or list of files the next translation comes from. This is the easiest kind of comment to implement. If two translations with the same msgid are found, they're merged into one translation and both source files are listed here.

```po
#: my_app/lib/foo.ex:84 my_app/lib/bar.ex:40
...
```

**Flag**: a list of flags/tags/format directives. Mostly used to denote the source language. We'll most likely automatically add `elixir-format` here.

```po
#, elixir-format
...
```

**Fuzzy**: related to the `fuzzy` flag. Let's just leave this alone for now :|

We're going to add a `:comments` field to the `PluralTranslation` and `Translation` structs, I'll think about the data structure for this. I'd go for a simple map or a `Comments` struct, but we have to decide if the original order of comments found in PO files matters to us (when re-creating the PO files back). If it does, we can go with a list of tagged tuples like `[{:reference, ...}, {:flags, ...}]`. We'll see :)

**Comment by josevalim** [comment]
This sounds great. Do we need to use flag? I think we can safely skip it... otherwise it is just noise in the .po files.

**Comment by whatyouhide** [comment]
I'll see how po editors behave when there's no flag comment. We could actually also use it to easily detect translations we generated instead of having to read the reference comment and search for `.ex` files.

**Comment by whatyouhide** [comment]
#18 implements support for both tokenizing and parsing comments. As of now, the process is very "rude": we just determine the type of the comment (only reference and translator comments are supported for now) and we tag its contents with it. For example, a reference comment like:

```po
#: lib/foo.ex lib/bar.ex
```

becomes `{:reference, " lib/foo.ex lib/bar.ex"}`. This is fine for translator comments (since we don't care about the contents of the comments) but we should parse other comment types deeper. The last example should come out as something like `{:reference, ["lib/foo.ex", "lib/bar.ex"]}`.
I'm not 100% sure where to do this: should we do it in the yecc parser or later in the `Parser` module, going through all the comments again?

**Comment by josevalim** [comment]
Btw, what gettext advises? To have a single reference line? Or to have one line per reference, as in:

    #: lib/foo.ex
    #: lib/bar.ex

I am asking because paths could have new lines in them, if that is the case, how they are handled?

Regarding where this logic may be implemented, any approach is fine. Maybe it is easier if the yecc just retrieves the commands "#..." and you extract the information from them in Elixir land.

**Comment by whatyouhide** [comment]
Ok, so, most of the material I'm reading about gettext says that when you have the same string from multiple locations, you just merge all of them into a single translation and list all the sources in a single reference comment:

```po
#: lib/foo.ex lib/bar.ex
```

I couldn't find anything on multiple reference comments, but I guess you can also do what @josevalim suggested:

```po
#: lib/foo.ex
#: lib/bar.ex
```

This *has* to be supported in one way or another, even if only for not writing overly long lines in the PO file:

```po
#: lib/foo.ex lib/bar.ex [another 100 files = very very long line]
```

I couldn't find anything about newlines in paths though. I guess you could escape filenames like you escape strings? `#: lib/foo\nbar.ex` becomes `"lib/foo" <> <<?\n>> <> "bar.ex"` to be clear.


One more thing, @josevalim you said:
> Maybe it is easier if the yecc just retrieves the commands "#..." and you extract the information from them in Elixir land.

Do you mean that in your opinion we should only create *one* comment token (`{:comment, line, contents}`), "ignore" it in yecc (i.e., leave it unchanged) and then go through all the parsed translations and give types to these tokens in Elixir (in `Gettext.PO.Parser`)?

**Comment by josevalim** [comment]
Yeah, one per line sounds much cleaner.

What about line numbers? We don't store the line with the reference? Wouldn't that be useful?

> Do you mean that in your opinion we should only create one comment token ({:comment, line, contents}), "ignore" it in yecc (i.e., leave it unchanged) and then go through all the parsed translations and give types to these tokens in Elixir (in Gettext.PO.Parser)?

We could create one token per line but extracting the semantic behaviour of the comment could be done in Elixir. If we go with my suggestion in the pull request, it could even be a completely separate stage, i.e. the parser extracts the comments but another step would look at the comments and attach the other info to the translation. Again, it is hard to say for sure until we start work on merging and what not.

**Comment by whatyouhide** [comment]
I keep forgetting about the line to store with the reference :) Consider all the code snippets I wrote as if they had a line as well:

```po
#: lib/foo.ex:34 lib/bar.ex:43
```

We could store each reference on a separate line, and store references pointing to the same file (but different lines) in different lines:

```po
#: lib/foo.ex:23 lib/foo.ex:97
#: lib/bar.ex:10
```

It's unlikely to have the same literal string many times in the same file, I guess people would tend to use a module attribute in that case.

**Comment by josevalim** [comment]
@whatyouhide you can't use it as a module attribute because the translation needs to happen at runtime. :) I would go with one reference per line so we don't need to worry about escaping and similar things for now. It is the simplest approach I think.

**Comment by whatyouhide** [comment]
We use `Macro.expand` so we should be covered in that sense, right?

**Comment by josevalim** [comment]
@whatyouhide I probably misunderstood you, sorry. What I mean is:

This is ok:

    @translation "hello"
    gettext @translation

This is bad:

    @translation gettext "hello"

:)

**Comment by whatyouhide** [comment]
Ah, right, that wouldn't work. Anyways, let's go with one reference per line for now and we'll see how it goes :)

**Comment by whatyouhide** [comment]
For reference, 2722c456b600df1b406603540fe1155c4e9fae25 implements what me and @josevalim have been discussing here and in #18, namely the single comment token type (`{:comment, line, contents}`) and the new `:references` field type for translations.

**Comment by whatyouhide** [comment]
I'm going to close this for now as comment support has been merged in `master`, we'll reopen it if we need further discussion.
