### ISSUE TITLE
Translations with no references are considered as inputted by the user

### ISSUE THREAD

**Issue by whatyouhide** [elixir-lang/gettext#162]
Since we added the option to output files without references in #161, we need to find a new way to mark translations that are "autogenerated" versus ones that are inserted manually by the user.

\cc @josevalim if you have ideas, shoot :)

**Comment by josevalim** [comment]
@whatyouhide folks that are disabling the reference comments can figure it out. :P

**Comment by josevalim** [comment]
Oops, I didn't meant to close it though. :)
