### ISSUE TITLE
Generating and merging PO(T) files

### ISSUE THREAD

**Issue by whatyouhide** [elixir-lang/gettext#17]
Opening this issue to lay down what @josevalim and I discussed yesterday. So, the next part in the development of Gettext for Elixir will be focused on compile-time niceties. These include automatic generation of POT and PO files as well as merging of such files.

First of all, just as a reference, POT files are just like PO files but with empty translations. Example of snippet of POT file:

```po
msgid "Hello there!"
msgstr ""

msgid "One error"
msgid_plural "%{count} errors"
msgstr[0]
msgstr[1]
```

The first step for implementing all of this will be to create a `Gettext.PO` struct that will represent a PO file. We need this since PO files contain translations as well as metadata (headers at the top of the file).

After we have a `Gettext.PO` struct in place, we'll create the code that dumps an instance of this struct as a PO(T) file. The goal (and the ultimate test) will be to make this true:

```elixir
dump(parse(file)) == file
```

## Merging PO(T) files

Once this is done, the next step will be to write code that *merges* two PO(T) files. This is probably the trickiest thing to do. PO(T) files will be merged every time the user runs whatever task we'll provide and some PO(T) files already exist. During this step, we'll do this:

* add all the new translations found in the source code
* remove all the old translations that are not in the source code anymore; we'll only remove the translations with a `#: reference` comment (see #16 for some info on comments) assuming that we automatically generated them
* leave translations without a reference comment untouched, even if they're not in the source code anymore

## Generating PO files

This will be pretty easy at this point. We just need to tweak the `*gettext` macros we have now so that we know all the translations at compile time.

## The future...

We can probably refine the process of merging PO(T) files, for example by not removing translations based on string similarities.

---

This is everything I remember from our conversation, @josevalim if I missed something add it here so we have everything in one place :).

**Comment by josevalim** [comment]
That sounds great. It is worth mentioning that merging pot and po files are very similar except that:

1. If a translation has no reference in .pot files, we won't remove them

2. If a translation has no reference in .po files, we still remove them, because we assume .pot files is the canonical source

Besides that, the process should be exactly the same.

**Comment by whatyouhide** [comment]
I'm closing this: the only thing left to implement from this issue is the generation of the PO(T) files and I opened #26 to give space to a more focused discussion on that.
