### ISSUE TITLE
elixir-format comment is removed when mix gettext.extract --merge runs again

### ISSUE THREAD

**Issue by manukall** [elixir-lang/gettext#171]
as far as i understand, `elixir-format` is used to indicate that a string was programmatically added to the po/pot files. however, when `mix gettext.extract --merge` is run again, those comments are removed, which i assume is not intended.

we're using the `write_reference_comments: false` flag, in case that makes a difference.

**Comment by whatyouhide** [comment]
Hey @manukall, could you provide a simple sample application with steps to reproduce this? It would be super helpful in debugging it and pushing a fix. :)

**Comment by manukall** [comment]
@whatyouhide sure: https://github.com/manukall/gettext_no_comments

there are gettext strings in `lib/gettext_no_comments.ex`.

to reproduce, uncomment `gettext("foo")` and run `mix gettext.extract --merge` again.

the result is, that the `#, elixir-format` comment is removed from the `msgid "world"` line in `priv/gettext/default.pot`. 
when you run the mix task again, it'll get removed from the new "foo" string as well.

hope that helps.

**Comment by whatyouhide** [comment]
It definitely helped, thanks @manukall!

**Comment by manukall** [comment]
Thanks ❤️
