### ISSUE TITLE
Public API for lgettext? To know what you get back: translation or msgid

### ISSUE THREAD

**Issue by ZombieHarvester** [elixir-lang/gettext#177]
There is a use case for dynamic translations. And a use case for static translations which cannot be extracted by `gettext.extract` (ecto validations for example)

In both cases you have to manage `.pot` entries manually which is error prone, as its is easy to miss a value to translate. 

`gettext` returns either translation or msgid. There is no way for you to know if the value was translated. (I haven't found any in public api at least, please let me know if i missed it). I need to know that translation is missing before i learn it from my users.

So i started using `lgettext` (which i know is wrong cause its internal api), but at least it returns `{:ok, translation}` or `{:default, msgid}`. So i can notify myself that translation is missing

```
    result = lgettext(locale, @domain, msgid, %{})

    case result do
      {:ok, translation} ->
        translation
      {:default, msgid} ->
        log_translation_missing(msgid)
        humanize(msgid)
    end
```

It would be nice to have a public api for that. Thanks

**Comment by josevalim** [comment]
Maybe a better idea is to add `handle_missing_translation` to the backend that receives all of the information and decides what to return.

Thoughts @whatyouhide?

**Comment by whatyouhide** [comment]
We already have `handle_missing_bindings` so I think it would make sense. We already have `catch_all/3` and `catch_all_n/5` helpers, so it's just a matter of introducing `handle_missing_translation` to the backend and default to what `catch_all_*` do today. I'll try to work on this tonight, but if you want to go ahead and make a PR @ZombieHarvester please do! 💟

**Comment by whatyouhide** [comment]
@josevalim should we go with `handle_missing_translation(locale, domain, msgid, bindings)` and `handle_missing_translation(locale, domain, msgid, msgid_plural, n, bindings)`, or go with an exception like we have for `handle_missing_bindings`? In the exception we would still need a way to tell translations from plural translations.

**Comment by josevalim** [comment]
@whatyouhide good question. I think we can keep the building of the exception reasonably fast, so I would with that too.
