### ISSUE TITLE
Pluralization custom forms on merger

### ISSUE THREAD

**Issue by gguerrero** [elixir-lang/gettext#179]
Some web translation providers still using `-` for country locales keys, e.g `es-ES` or `pt-BR`.
For pluralization, gettext uses underscore form with the following [doc explanation](https://hexdocs.pm/gettext/Gettext.Plural.html#module-language-and-country.):

> Often, a locale is composed as a language and country couple, such as en_US. The default implementation for Gettext.Plural handles xx_YY by forwarding it to xx (except for just Brazilian Portuguese, pt_BR, which is not forwarded to pt as pluralization rules slightly differ). We treat the underscore as a separator according to ISO 15897. Sometimes, a dash - is used as a separator (for example, en-US): this is not forwarded to en in the default Gettext.Plural (and it will raise an Gettext.Plural.UnknownLocaleError exception).

With that says, I was trying to define a custom pluralizer for solving the problem like this:
```elixir
defmodule MyApp.Plural do
  @behaviour Gettext.Plural

  def nplurals("es-ES"), do: 2
  def nplurals("pt-BR"), do: 2
  def nplurals(locale), do: Gettext.Plural.nplurals(locale)

  def plural("es-ES", 1), do: 0
  def plural("es-ES", _n), do: 1
  def plural("pt-BR", n) when n in [0, 1], do: 0
  def plural("pt-BR", _n), do: 1
  def plural(locale, n), do: Gettext.Plural.plural(locale, n)
end

defmodule MyApp.Gettext do
  use Gettext, otp_app: :my_app, plural_forms: MyApp.Plural
end
```

This solved the problem in the app context but, when executing the merger task still failing:
```
$ mix gettext.merge priv/gettext
Wrote priv/gettext/es-ES/LC_MESSAGES/errors.po
** (EXIT from #PID<0.73.0>) an exception was raised:
    ** (Gettext.Plural.UnknownLocaleError) unknown locale "es-ES". If this is a locale you need to handle,
consider using a custom pluralizer module instead of the default
Gettext.Plural. You can read more about this on the Gettext docs at
https://hexdocs.pm/gettext/Gettext.Plural.html

        lib/gettext/plural.ex:658: Gettext.Plural.recall_if_country_or_raise/2
        (elixir) lib/keyword.ex:576: Keyword.put_new_lazy/3
        lib/gettext/merger.ex:163: Gettext.Merger.new_po_file/5
        lib/mix/tasks/gettext.merge.ex:184: anonymous fn/5 in Mix.Tasks.Gettext.Merge.merge_dirs/5
        (elixir) lib/task/supervised.ex:88: Task.Supervised.do_apply/2
        (elixir) lib/task/supervised.ex:38: Task.Supervised.reply/5
        (stdlib) proc_lib.erl:247: :proc_lib.init_p_do_apply/3
```
As you can see in the backtrace, the merger is not taking my app custom pluralizer, so my country locales are not found. That happens here:

https://github.com/elixir-lang/gettext/blob/9790c476ae1cccdf8974342b3624e535ff822be2/lib/gettext/merger.ex#L194

I think the merger module should be fixed to take the app custom pluralizer rather than the lib original one.
Also would be even better IMO if also `-` is still accepting as country locale separator with maybe a warning/deprecation message rather than an exception.

**Comment by whatyouhide** [comment]
> I think the merger module should be fixed to take the app custom pluralizer rather than the lib original one.

We cannot read the custom pluralizer when merging because we don't know which backend the files that we're merging belong to (and the pluralizer is an option given to each Gettext backend). This is indeed a bug but the solution is to just default to using two plural forms for all unknown locales.

Maybe we should warn for this particular case @josevalim?

In any case @gguerrero, are you interested in submitting a PR with the fix that I mentioned?

> Also would be even better IMO if also - is still accepting as country locale separator with maybe a warning/deprecation message rather than an exception.

I would prefer to keep a single format for simplicity, so for now I would say no on this.

**Comment by josevalim** [comment]
I would also recommend maybe keeping different locales internally, one that you pass to gettext and another used by your app. There is no reason to couple the two.

In any case, if someone is still being bitten by this and would like us to get rid of the error, please get in touch.
