### ISSUE TITLE
mix gettext.extract --merge not work

### ISSUE THREAD

**Issue by zmcNotafraid** [elixir-lang/gettext#183]
I upgrade version to 0.15. And I run
```
 mix gettext.extract --merge
```
But it only modify .pot file.And no .po file is been changed.
When I run
```
mix gettext.extract
mix gettext.merge priv/gettext
```
It's ok

**Comment by whatyouhide** [comment]
Hey @zmcNotafraid, looking at the Gettext code it seems that should work. Could you either upload a minimal reproducing example somewhere, or show us the directory tree for your project (or parts of it)? We need a bit more info to try and debug this :). Thanks for reporting! 💟

**Comment by abitdodgy** [comment]
I can reproduce this. Running `mix gettext.extract --merge` does not modify the .po file.

**Comment by abitdodgy** [comment]
May this is a concurrency issue?

**Comment by zmcNotafraid** [comment]
My directory tree is lib/priv/gettext/. When I run ```mix gettext.extract --merge```
The terminal only show ```Extracted priv/gettext/```, but no merge info.
And I read the code that find lib/mix/tasks/gettext.extract.ex has been modified.
So I guess maybe  async stream cause the issue.
