### ISSUE TITLE
[question] Where do we put dynamic translations?

### ISSUE THREAD

**Issue by abitdodgy** [elixir-lang/gettext#188]
I have dynamic translations in some places (like a page sorter, where the params are used to show the current sort options). The docs advise us to use Gettext functions for such cases. By using `mix gettext.extract --merge`, however, dynamic translations are removed from `.pot` and `.po` files.

In other words, if you don't use macros, any translations manually added to `.po` and `.pot` files are deleted after running extract and merging.

Here's an example:

```eex
  <%= link to: "#/", class: "dropdown-toggle", data: [toggle: "dropdown"] do %>
    <%= if @conn.params["sort"] do %>
      <% msgid = "#{@conn.params["sort"]["column"]} #{@conn.params["sort"]["direction"]}" %>
      <%= Gettext.dgettext(ObramaxWeb.Gettext, "carts", msgid) %>
    <% else %>
      <%= dgettext "carts", "Order" %>
    <% end %>
  <% end %>
```
And in the .po file:

```
#, elixir-format
#: lib/obramax_web/templates/telesales/product/sorter.html.eex:5
#: lib/obramax_web/templates/telesales/product/sorter.html.eex:15
msgid "description asc"
msgstr "Descrição Ascendente"
```

If I run `mix gettext.extract --merge`, the dynamic translations above disappear.

Where are we supposed to put dynamic translations, in this case, or am I going about this the wrong way?

**Comment by whatyouhide** [comment]
Also, I believe that from the next released version of Gettext we will use a `elixir-format` tag to decide if Gettext added the translations, so this issue can likely be closed by just releasing the new version :P

**Comment by abitdodgy** [comment]
@whatyouhide I'll give it a shot and let you know. @josevalim thanks for the suggestion.

**Comment by whatyouhide** [comment]
@abitdodgy we just released a new version of Gettext. Please update as it should fix your problem. I'll go ahead and close this issue. Please feel free to comment here or reopen it if the latest version is still causing problems. Thanks for reporting!

**Comment by rrrcompagnoni** [comment]
@abitdodgy I've had this issue recently. The dynamic translations were being removed from my pot files. You can rely on pattern matching to achieve the desired behaviour. 

Instead of:
```
defmodule MyApp.RegistrationStatus do 
  def to_string(status) do
    MyApp.Gettext.dgettext("registration_statuses", status)
  end
end
```
Try:
```
defmodule MyApp.RegistrationStatus do 
  def to_string(:pending), do: MyApp.Gettext.dgettext("registration_statuses", "pending")
  def to_string(:approved), do: MyApp.Gettext.dgettext("registration_statuses", "approved")
  def to_string(_), do: MyApp.Gettext.dgettext("placeholder", "missing")
end
```
