### ISSUE TITLE
Documentation site: search not working

### ISSUE THREAD

**Issue by sfusato** [elixir-lang/gettext#189]
1. The search feature is not working:
[https://hexdocs.pm/gettext/search.html?q=gettext](https://hexdocs.pm/gettext/search.html?q=gettext) returns nothing, for example.

2. The styling also seems  a bit off when compared to Elixir/Phoenix/Ecto documentations (screenshot attached: search field, toggle sidebar)
![gettext](https://user-images.githubusercontent.com/19363153/44863771-b52cb000-ac86-11e8-8dc0-50f03d9b786c.PNG)

**Comment by josevalim** [comment]
@whatyouhide shall we release a new version and update to ex_doc 0.19.0 in the process?

**Comment by whatyouhide** [comment]
@josevalim on it.

**Comment by whatyouhide** [comment]
Done! https://hex.pm/packages/gettext/0.16.0
