### ISSUE TITLE
Default locale is wrong, and locale is not used 

### ISSUE THREAD

**Issue by Cochonours** [elixir-lang/gettext#192]
I am testing the water with phoenix (1.4) / gettext (0.16.0) and I want my web page to specify the language as an attribute on the html tag. So I write this : 
`<html lang="<%= Gettext.get_locale() %>">`

First problem: it appears that get_locale() returns "en" even though my browser asks for "fr" (my Accept-Language header is : "fr,en-US;q=0.7,en;q=0.3").

Second problem: even though it says "en", it really is "fr" as the text appears in French (I set it as the default locale for this project). So the locale is not used by Gettext to retrieve the right translations.

As a temporary fix, I found out that putting `Gettext.put_locale(Gettext.get_locale())` above the rest seems to remind gettext that indeed the locale returned by "get_locale" should be used (it's setting the locale as "en" every time because of the first problem, but at least I can see it works if I force put_locale with a string param).

**Comment by josevalim** [comment]
Can you please provide a sample app that reproduces this? It is weird that
calling put_locale with the current locale is changing things.

Also, keep in mind Phoenix does not automatically set the locale based on
the header. That’s up to you to implement although most people suggest to
not do that generally. It is best if the locale is in the URL and you read
the header only on first access.
-- 


*José Valim*
www.plataformatec.com.br
Skype: jv.ptec
Founder and Director of R&D

**Comment by Cochonours** [comment]
Ok for the first problem then.. I assumed it would as guessing the locale from the header is not uncommon at all. I am going to implement something that uses the URL indeed, but when someone comes to the root of the website, there is no better way than using his Accept-Language info to serve the page.

Back to the real bug, how would you like me to send the app? Zip it all and send (I do not use github/etc.)? It's really basic at the moment, and the only thing I changed was putting : 
`
config :toto, TotoWeb.Gettext,
  default_locale: "fr",
  locales: ~w(fr en es ko)
`
in "config.exs", and creating the different po/pot files.

**Comment by josevalim** [comment]
>  there is no better way than using his Accept-Language info to serve the page

Agreed. Note it is also common to add a cookie if the user ever explicitly pick another language. So the fallback is usually `url || cookie || header`.

Oh, I see. the reason why the erreor is happening is because you are using `Gettext.get_locale`, which sets the global gettext locale, but you have configured the locale on a specific backend, so you should do `Gettext.get_locale(TotoWeb.Gettext)` instead. Or you configure the locale globally:

    config :toto, default_locale: "fr"

**Comment by Cochonours** [comment]
Oh, that's it! 

What would you recommend, setting it globally or keeping it local?

Thanks a lot

**Comment by josevalim** [comment]
Actually, my feedback above was wrong. If you want global, you should set it as:

    config :gettext, default_locale: "fr"

I am currently considering deprecating the local configuration one, so I would go with the global one.
