### ISSUE TITLE
dgettext crashes on 0.16.1

### ISSUE THREAD

**Issue by jfayad** [elixir-lang/gettext#194]
With the 0.16.1 release the following behaviour is occuring:

```iex(1)> import ZaqWeb.Gettext
ZaqWeb.Gettext
iex(2)> ZaqWeb.Gettext.dgettext("zaq","test")
** (FunctionClauseError) no function clause matching in ZaqWeb.Gettext.__gettext__/1    
    
    The following arguments were given to ZaqWeb.Gettext.__gettext__/1:
    
        # 1
        :default_locale
    
    Attempted function clauses (showing 3 out of 3):
    
        def __gettext__(:priv)
        def __gettext__(:otp_app)
        def __gettext__(:known_locales)
    
    (zaq_web) lib/zaq_web/gettext.ex:1: ZaqWeb.Gettext.__gettext__/1
    (gettext) lib/gettext.ex:675: Gettext.dgettext/4
```

downgrading to 0.16.0 solves the issue.

Running it from an app shows that the error originates from this line
`(gettext) lib/gettext.ex:675: Gettext.dgettext/4`

**Comment by josevalim** [comment]
Can you please remove `_build` and let us know if the issue persists? Thanks.

**Comment by jfayad** [comment]
Hello @josevalim indeed, removing the _build directory and recompiling the project from scratch with the latest version fixed it. Thanks for the hint.

wondering why are the build files interfering with new versions of packages and producing such inconsistent results ?

**Comment by josevalim** [comment]
@jfayad Mix was supposed to pick it up. If you can consistently reproduce this, then please let me know how and I would love to investigate it.
