### ISSUE TITLE
Translations get overwritten with multiple Phoenix endpoints in a single application

### ISSUE THREAD

**Issue by florish** [elixir-lang/gettext#196]
I’m having some trouble with Gettext in combination with an Elixir app with multiple Phoenix endpoints. 

All `msgid`s found in the first namespace (say: `AaaWeb`) seem to be overwritten in case any `msgid` is found in the second namespace (say: `BbbWeb`).

Example with .pot file output:

I have two templates with a `gettext/1` marker:

1. lib/aaa_web/templates/foo/show.html.eex
```
<%= gettext("Foo") %>
```

2.  lib/bbb_web/templates/bar/show.html.eex
```
<%= gettext("Bar") %>
```

Expected output in `priv/gettext/default.pot` (header comments omitted):
```
#, elixir-format
#: lib/aaa_web/templates/foo/show.html.eex:1
msgid "Foo"
msgstr ""

#, elixir-format
#: lib/bbb_web/templates/bar/show.html.eex:1
msgid "Bar"
msgstr ""
```

Actual output in `priv/gettext/default.pot` (again, header comments omitted):
```
#, elixir-format
#: lib/bbb_web/templates/bar/show.html.eex:1
msgid "Bar"
msgstr ""
```

So "Foo" is missing. Generally speaking, it seems like all entries found in the `aaa_web` namespace are overwritten with entries found in `bbb_web`. 

I also tried with `dgettext/2`, and the same applies. Interestingly, entries found in `aaa_web` for a domain that has no entries in `bbb_web` are preserved. Once I add a single `msgid` for the same domain in `bbb_web`, all msgids found in `aaa_web` are gone.

Is this a bug? Or maybe there is a configuration setting I'm missing?

**Comment by josevalim** [comment]
@florish are you running those commands from the umbrella root? Or inside each individual app? Can you also provide a simple application that reproduces this issue? Thanks!

**Comment by florish** [comment]
@josevalim Quick reply: it's not an umbrella app, just a normal Phoenix 1.4 app as created with `phx.new`. The app does have multiple Phoenix endpoints configured, each with their own `_web` directory structure containing controllers, views, templates, etc.

I'll create a simple example application for reproduction.

**Comment by florish** [comment]
@josevalim Here's an example app demonstrating the issue:

https://github.com/florish/elixir-gettext-example-project

The last commit contains the result of running `mix gettext.extract --merge` after adding a second `Endpoint`.

Hope this helps! Let me know if you need any additional information.

**Comment by florish** [comment]
@josevalim By coincidence, one of my co-workers discovered were the error was coming from.

On adding a second Phoenix endpoint, we simply copied over files from the first endpoint (in the example: files in the `aaa_web` folder) and renamed the top-level module. As part of that, we also duplicated the `Gettext` module:

```elixir
# lib/aaa_web/gettext.ex
defmodule AaaWeb.Gettext do
  use Gettext, otp_app: :aaa
end

# lib/bbb_web/gettext.ex
defmodule BbbWeb.Gettext do
  use Gettext, otp_app: :aaa
end
```

Both `Gettext` modules refer to the same `:otp_app`, as there only is one. In hindsight, this should have been a hint that there should only be one `Gettext` instance for both endpoints, as the project only contains a single OTP Application.

We've changed this in our real-life project and now `msgid`s from both `_web` folders show up in the .pot and .po files on running `mix gettext.extract --merge`.

As we did not receive any warnings about defining duplicate `Gettext` modules for the same OTP app, there might still be value in adding such a warning to `gettext`. I'm leaving it up to the package authors to decide on this and to close this issue.

**Comment by josevalim** [comment]
Thanks for the follow up. I agree we can probably detect if there is more than one endpoint per app when running those tasks and warn that only of those will prevail.

**Comment by joeystl434** [comment]
I have a similar problem but within an umbrella. Is it possible to centralize multiple app translations into a single translation app? I tried many things but I haven't managed to get more than one of the apps' translations.
