### ISSUE TITLE
Documentation site for 0.16.1 seems to be broken

### ISSUE THREAD

**Issue by zentetsukenz** [elixir-lang/gettext#198]
I see #189 fixed 0.16.0 release. However, the same issue with CSS and search comes back in version 0.16.1

<img width="1264" alt="Screen Shot 2019-03-10 at 6 39 57 PM" src="https://user-images.githubusercontent.com/2451278/54084503-0ddeb300-4364-11e9-830f-1be0a2f4cdfc.png">

Did some quick look but haven't found anything odd [0.16.0..0.16.1 diff](https://github.com/elixir-lang/gettext/compare/v0.16.0...v0.16.1).

**Comment by josevalim** [comment]
Update ExDoc and repushed.
