### ISSUE TITLE
Using gettext for external files?

### ISSUE THREAD

**Issue by strzibny** [elixir-lang/gettext#200]
Hello all,

I was thinking of using gettext to translate an external file (a template, regular file with `gettext()` calls for example). Is this possible?

The API I have in mind:
```
translated = gettext_file("path/to/file", "locale")
```
My use-case is an API documentation and I was thinking to use the gettext and regular gettext Phoenix setup to do so (implemented as Mix task).

**Comment by josevalim** [comment]
Is the external file a regular Elixir file?
-- 


*José Valim*
www.plataformatec.com.br
Skype: jv.ptec
Founder and Director of R&D

**Comment by strzibny** [comment]
No, it's a `.apib` blueprint (format to describe APIs), but I was thinking making it a `.eex` template from which I would generate more blueprint files -- one per each supported language. 

Does it make sense José?

**Comment by josevalim** [comment]
Gettext works by executing Elixir code. So as long as you run or embed the
templates into source files while your Elixir code is compiled, gettext
will be able to pick it up.
-- 


*José Valimwww.plataformatec.com.br
<http://www.plataformatec.com.br/>Founder and Director of R&D*

**Comment by josevalim** [comment]
Closing per the above. ^

**Comment by strzibny** [comment]
Yes, I realize it's more about the EEx context probably than gettext question. I have the following task:

```
defmodule Mix.Tasks.MyApp.GenerateApiDocs do
   import MyApp.Gettext

   use Mix.Task

   @shortdoc "Generate documentation"
   @moduledoc ~S"""
   """
   def run(_args) do
      Mix.shell.info "Generating translated Blueprint files..."

      Gettext.with_locale MyApp.Gettext, "cs", fn ->
        # works
        IO.inspect gettext("title v1")
        # fails
        apib = EEx.eval_file "priv/api/v1/api_v1.gettext.apib", [gettext: &MyApp.Gettext.gettext/1]
     end

     Mix.shell.info "Done."
   end
end
```
Template:
```
FORMAT: 1A

# <%= gettext("title v1") %>
```
It probably cannot find the definitions:
```
== Compilation error in file lib/mix/tasks/generate_api_docs.ex ==
** (ArgumentError) Gettext macros expect translation keys (msgid and msgid_plural),
domains, and comments to expand to strings at compile-time, but the given msgid
doesn't. This is what the macro received:

{:x1, [line: 25], :elixir_fn}

Dynamic translations should be avoided as they limit Gettext's
ability to extract translations from your source code. If you are
sure you need dynamic lookup, you can use the functions in the Gettext
module:
...
```

**Comment by josevalim** [comment]
You can't pass a macro as a function, because then you are hiding its actual arguments. You need to `<% import Gettext %>` at the top of your template.
