### ISSUE TITLE
No v0.17.0 tag?

### ISSUE THREAD

**Issue by evadne** [elixir-lang/gettext#202]
Hello

Was there a tag for `v0.17.0`?

At the moment, documentation pages that link to sources are broken, for example: https://hexdocs.pm/gettext/Gettext.html#dgettext/3 links to https://github.com/elixir-lang/gettext/blob/v0.17.0/lib/gettext.ex#L1 which implicitly requires presence of the `v0.17.0` tag.

Thanks.

**Comment by josevalim** [comment]
Fixed, thanks!
