### ISSUE TITLE
Dialyzer errors on `Gettext.PO.parse_string`

### ISSUE THREAD

**Issue by hauleth** [elixir-lang/gettext#205]
Currently Dialyzer states that:

```elixir
{:ok, _} = Gettext.PO.parse_string(string)
```

will always fail, as this function always return `{:error, non_neg(), binary()}`.

**Comment by josevalim** [comment]
Thanks for the report. We don't use dialyzer ourselves, so a PR is welcome!

**Comment by hauleth** [comment]
@josevalim you mean PR that fix the issue or that will run Dialyzer on CI?

**Comment by josevalim** [comment]
That fixes the issue, thanks!
-- 


*José Valimwww.plataformatec.com.br
<http://www.plataformatec.com.br/>Founder and Director of R&D*

**Comment by josevalim** [comment]
Ping. :D

**Comment by hauleth** [comment]
Hell, I have forgotten about it. I will try to write something.

**Comment by whatyouhide** [comment]
@hauleth we don't really use Dialyzer. If you get time to work on something we'd appreciate it. Closing the issue in the meantime, thank you!

**Comment by kenny-evitt** [comment]
I just created a pull request that resolves this warning, and several others:

 - [Fix spec and update doc for one function by kenny-evitt · Pull Request #230 · elixir-gettext/gettext](https://github.com/elixir-gettext/gettext/pull/230)

@whatyouhide @josevalim Are you interested in using Dialyzer for this project?

**Comment by josevalim** [comment]
We are not, as we usually don't have Dialyzer in our workflows. Thanks for asking though!
