### ISSUE TITLE
The --no-fuzzy part of mix gettext.extract is not working

### ISSUE THREAD

**Issue by evadne** [elixir-lang/gettext#211]
Within `Mix.Tasks.Gettext.Extract`, `args` are rebound straight away when parsing options for extraction. Therefore`Mix.Tasks.Gettext.Merge`, invoked if the `--merge` option is given, never gets the `--no-fuzzy` argument.

**Comment by josevalim** [comment]
Good catch! Can you send a PR please? :)
-- 


*José Valim*
www.plataformatec.com.br
Skype: jv.ptec
Founder and Director of R&D

**Comment by evadne** [comment]
If I instead use the invocation `mix gettext.extract --merge -- --no-fuzzy` then everything works. Perhaps that is a better solution than fixing the parsing bits?

**Comment by josevalim** [comment]
I think for simplicity we should rather keep the original `args` around and pass them forward. I am at the computer now, so I can push a fix. :)
