### ISSUE TITLE
Collecting translations from the *gettext family of macros

### ISSUE THREAD

**Issue by whatyouhide** [elixir-lang/gettext#26]
I think this is almost the last step before a first usable version of Gettext, so I'm excited to discuss this topic :D

So, we need to generate POT files from calls to the `*gettext` family of macros. We already have these macros working, so the work we have to do in the macros themselves is probably just a matter of adding a couple lines to each macro:

```elixir
defmacro gettext(...) do
  # ...
  if we_want_to_collect_translations do
    Gettext.Collector.collect(translation)
  end
  # ...
end
```

@josevalim, @ericmj, and I discussed possible strategies for "triggering" this POT file generation at ElixirConfEU 2015. These are the alternatives I remember from the conversation:

* always generate POT files, whenever compilation happens. I'm not a fan of this strategy since, as José mentioned back then, it's probably better to be explicit and wait for the user to *ask* Gettext to collect translations.
* provide a new mix task that collects translations. This is the approach I like the most; we can start an agent or create an ETS table (or whatever storage we'll choose) when the task is executed, then force recompiling of the project (all translations are stored in the agent/ETS table) and finally generate the POT file and merge it with the existing PO(T) files. FWIW, I think if we choose the mix task route it would possibly be better to provide a separate task for merging the new POT file with the old PO files so that users are free to merge them with other tools if they want to; for example, `mix gettext.pot` and `mix gettext.merge_po` or something on these lines.

I can't remember anything else from the conversation :( What are your ideas on this?

**Comment by josevalim** [comment]
Yes, we can do it by parts. The first one is definitely being able to collect such calls. After that, we need a function that will save merge those into pot fies in the configured directory. Just then we can start discussing how to integrate into user apps.

I can see benefits to both approaches, honestly. If I am working mostly in english, then I can generate it only from time to time. But if I am working on another language, I may want a faster cycle. But I think it may be possible to do it in a way that supports both. For example, if we have `compile.gettext`, people can call it directly or add it to their list of compilers.

**Comment by whatyouhide** [comment]
@josevalim using a custom `:gettext` compiler is a wonderful idea. Just a couple of questions:

* do you think using a dedicated Mix environment (`gettext` I would suggest) is a good idea for detecting whether to collect translations in the `*gettext` macros? I thought of a mix env just for simplicity but I'm not sure it would be a good idea if the `gettext` compiler is called while compiling the rest of the files as well.
* could you briefly walk me through what the Gettext compiler would look like? I mean, it would have to manually call the `:elixir` compiler with the `--force` option, right? We need to collect *all* the translations every time, not just the changed ones. Does that mess up the compilation process?

**Comment by josevalim** [comment]
I don't think we need a special Gettext environment.

I am not sure how it would look like yet. I think it could call `mix compile --force`. it will work if called directly but will be a no-op in case we call it as part of the compiler and then everything should work. But before we try it, it is hard to know.

**Comment by whatyouhide** [comment]
Closing this one as #27 implements `mix gettext.extract`.

**Comment by josevalim** [comment]
Let's leave it open so I don't forget of compile.gettext. :D

**Comment by whatyouhide** [comment]
@josevalim fair enough :)
