### ISSUE TITLE
Consider having default locale set is a must,

### ISSUE THREAD

**Issue by lexmag** [elixir-lang/gettext#48]
otherwise we need a more informative error message for a following case:
```elixir
iex(1)> Gettext.locale
nil
iex(2)> Gettext.with_locale("it", fn() -> end)
** (ArgumentError) locale/1 only accepts binary locales
    lib/gettext.ex:432: Gettext.locale/1
    lib/gettext.ex:568: Gettext.with_locale/2
iex(3)> Gettext.locale
"it"
```
As you see without `:default_locale` env var it fails to reset locale back.

**Comment by josevalim** [comment]
Yes, `Gettext.locale` always need to return something. It may just default to "en".

**Comment by josevalim** [comment]
I am also wondering if the locale configuration should really be in `Gettext.locale` or if it should be per backend.

**Comment by lexmag** [comment]
> locale configuration should really be in Gettext.locale or if it should be per backend
It feels more intuitive to have it per backend, and more flexible.

**Comment by whatyouhide** [comment]
I'm :+1: on making the locale per-backend. We can store it under `MyApp.Gettext` in the process dict and increment the arity of `locale/0-1` to `locale(backend)` and `locale(backend, locale)`. I'm not sure how we could configure it. We could use the Mix config for each backend:

```elixir
config :my_app, MyApp.Gettext, default_locale: "pt_BR"
```

and also default to `"en"` if there's no config (which is the subject of the issue).

What do you think?

**Comment by josevalim** [comment]
:+1: for everything. Will we also have `MyApp.Gettext.locale/0/1`?

**Comment by lexmag** [comment]
That's sounds wonderful.

**Comment by whatyouhide** [comment]
@josevalim I wouldn't provide both `Gettext.locale/1-2` and `MyApp.Gettext.locale/0-1` because they would do the exact same thing (but we would still have to test/document all of them). Also, we'd need to introduce `MyApp.Gettext.with_locale/2` as well. Wdyt?

**Comment by lexmag** [comment]
I do see the need for `MyApp.Gettext.with_locale/2`, not sure if we need `MyApp.Gettext.locale/0-1` though.

**Comment by josevalim** [comment]
Ok, we don't need to add any of them. `Gettext.get_locale(backend)` & `Gettext.put_locale(backend, ...)` would be my votes. I think it would be nice to change the name so it is clearer now with multiple args and so we effectively break the users code, otherwise it can accidentally pass.

**Comment by whatyouhide** [comment]
Awesome, I'll come up with a PR soon.

**Comment by lexmag** [comment]
Ah, `get_` and `put_` verbs – that's nice.

**Comment by whatyouhide** [comment]
I was :+1: for `get_` and `put_` from the beginning so I'm happy about this change :)
