### ISSUE TITLE
gettext.extract --merge does not preserve default msgstr's

### ISSUE THREAD

**Issue by chrismccord** [elixir-lang/gettext#55]
I may be missing something, but when running `mix gettext.extract --merge` for the first time, I find all the message strings are blank. This results in all templates returning blank strings until I go fill in the translations. It seems like a better approach would be to have the msgid copied over to the msgstr. Thoughts?

Example of generated .po

```
#: web/views/page_view.ex:3
msgid "A productive web framework that does not compromise speed and maintainability."
msgstr ""

#: web/views/layout_view.ex:19
msgid "Get Started"
msgstr ""
```

Example of what I'd like to be generated:

```
#: web/views/page_view.ex:3
msgid "A productive web framework that does not compromise speed and maintainability."
msgstr "A productive web framework that does not compromise speed and maintainability."

#: web/views/layout_view.ex:19
msgid "Get Started"
msgstr "Get Started"
```

**Comment by josevalim** [comment]
The question is: do we want to automatically copy it for all idioms? Or just for english? And which one is a better default even for other languages, showing no text or showing the text in english?

It feels copying msgstr for the merge is indeed the best way to go.

**Comment by chrismccord** [comment]
I was thinking only for English, otherwise you'll have stray english fragments to track down when you make changes

**Comment by josevalim** [comment]
@chrismccord right. assuming you don't track those down, the website will show no text, which I think is worse even for non-english languages?

**Comment by whatyouhide** [comment]
The idea would be to turn a `.pot` (with blank strings) into a `.po` only when you're ready to translate all of the strings in the language of the new `.po`. Do you think people would use `""` as a translation on purpose for some reason? If not, we could just make gettext see `""` as untranslated strings, so that when it encounters one, it just returns the `msgid`. (I think I already proposed this a long time ago but we didn't think about it too much because it was a bit early in the life of gettext)

**Comment by endersstocker** [comment]
I like what @whatyouhide is proposing. It prevents the case of showing no text where no translation is yet provided, making it easy for a programmer to internationalize up front and defer localization. It also yields a translation file that a translator can more easily and intuitively complete (i.e., they don’t have to delete text or hunt for where they left off). It also facilitates piecemeal translation: where translations are missing in the `.po`, the string is empty.

**Comment by endersstocker** [comment]
While I doubt that intentional blank translations would be commonplace, we could allow `mgstr :blank`.

**Comment by endersstocker** [comment]
Also, the tools for working with `.po` files expect that a blank `msgstr` is awaiting translation (not one whose text matches its `msgid`). The portable object format and its generation is pretty clearly defined. Parsing those files is not. That’s where we can define new behaviour, such as translating `msgstr ""` as its `msgid`.

**Comment by whatyouhide** [comment]
@endersstocker the parsing may not be clearly defined, but I wouldn't do things like `msgstr :empty` or turning `msgstr ""` into `msgstr MSGID_HERE` in the parser (a lot of tools support reading/writing PO files and I want to mess them up as little as possible).

What I mean was doing this at a higher level, in the `l(n)gettext` functions: when we try to find a translation for `"foo"` in locale `"loc"` but get back `""`, then we fallback to the value of the `msgid`.

**Comment by endersstocker** [comment]
@whatyouhide I’m with you. I meant parsing in a broader sense.

**Comment by josevalim** [comment]
@whatyouhide just so I understand, do tools like poedit use things like `msgstr ""` to identify what needs to be translated? Couldn't use a comment for that (like we do with `# fuzzy`?

At first, replacing `""` makes me feel a bit uncomfortable. But if we don't have another option, then we don't have another option. :)

**Comment by whatyouhide** [comment]
@josevalim I'm not sure but when you take a `.pot` file and create a new `.po` file from that file using poedit, msgstrs are empty (`""`), so I guess this is the correct behaviour? I can't find a "filter" option in poedit to show what needs to be translated but when you make poedit check for problems with translations, it reports this:

<img width="407" alt="screen shot 2015-11-21 at 16 20 45" src="https://cloud.githubusercontent.com/assets/3890250/11319110/10e5daaa-906c-11e5-9e9e-b0143ed9224b.png">

The translations that it reports as "not translated yet" are just translations with empty `msgstr`.

**Comment by josevalim** [comment]
@whatyouhide so we should do it on our gettext side, you are right. If we have an empty string, we should show msgid.

**Comment by whatyouhide** [comment]
@josevalim yep. Should we warn somewhere for this kind of things? Something akin to `".po file for locale pt_BR exists but this translation is empty"`?

**Comment by josevalim** [comment]
If we are going to warn, then we need a way to copy the msgid to msgstr, at least for english based locales. Otherwise, I would go with no warning.

**Comment by whatyouhide** [comment]
Ok, #56 got merged so now the behaviour for translations with empty `msgstr` is to just default to the `msgsid`. (for plural translation, "empty msgstr" means one or more empty msgstrs)

**Comment by chrismccord** [comment]
:heart_eyes_cat:
