### ISSUE TITLE
msgid and msgid_plural must be string literals

### ISSUE THREAD

**Issue by TakteS** [elixir-lang/gettext#60]
How to use gettext dynamicly? I think code like:

```
string = "sample of string"
gettext string
```
have to work, because "string" variable return a string, it is logical, right?

**Comment by josevalim** [comment]
@whatyouhide we need to improve the error message. Dynamic lookup should be avoided. If you are sure you want dynamic lookup, use `Gettext.gettext(YourGettext.Module, string)`.

**Comment by whatyouhide** [comment]
@josevalim alright, makes sense. Working on it!

**Comment by TakteS** [comment]
@josevalim If it is incorrect way, how to better translate ecto validation errors? Or you planned add this feature in ecto by default?

**Comment by josevalim** [comment]
We are going to add somehting to Phoenix.Ecto soon but, in Ecto's case, the dynamic option via the `Gettext` module is the way to go. So you have our blessing :D

**Comment by TakteS** [comment]
Ok :smile:

**Comment by whatyouhide** [comment]
#61 should provide a much clearer error message in case this happens!
