### ISSUE TITLE
Add Gettext.known_locales(backend)

### ISSUE THREAD

**Issue by whatyouhide** [elixir-lang/gettext#62]
This function would return all the locales in a given backend for which there are PO files. This is useful to know in advance if the locale you want to translate to has translations file or if Gettext would fallback to english.

**Comment by TakteS** [comment]
The function should return a list like [{:domain, "msgid", "msgstr"}, ...]?

**Comment by josevalim** [comment]
It should return only the known locale names as atoms or strings (I don't
remember how they are kept internally).

-- 


*José Valim*
www.plataformatec.com.br
Skype: jv.ptec
Founder and Director of R&D

**Comment by TakteS** [comment]
How to get a current "priv" path in the Gettext module?

**Comment by whatyouhide** [comment]
@TakteS you mean how to get, given a `MyApp.Gettext` module, the directory from where that module is reading the PO files?

If so, the location for this module:

```elixir
defmodule MyApp.Gettext do
  use Gettext, otp_app: :my_app
end
```

is in the `priv` directory of the given `:otp_app` (`:my_app`): `Application.app_dir(:my_app, "priv")` is the priv directory and the files are by default in `priv/gettext`. You can also customize that option:

```elixir
defmodule MyApp.Gettext do
  use Gettext, otp_app: :my_app, priv: "translations"
end
```

Here, the translations are in `priv/translations` of `:my_app`.

**Comment by whatyouhide** [comment]
Closing for now as the issue mentioned adding `Gettext.known_locales/1` and it has been added by #63.

**Comment by thojanssens** [comment]
Can't we get a `Gettext.known_locales/0` without the backend?

In a library I'm coding, I want to retrieve all the _known locales_ of an application, that I use as default locales list for some multilingual things (e.g. library renders a list of text inputs, one per language, based on given locales list. If no locales list is given => default to `known_locales`).

If the user has to specify the backend, then it's not a default param anymore...

Actually honestly I don't really understand this backend thing, I guess it's used for multiple umbrella apps or something specific like this. When I look at my priv/gettext folder, it doesn't seem to be divided into groups(backend). So it would be nice to have the functions without the backend.

**Comment by josevalim** [comment]
Having the functions without a backend means singleton/global state. And it means you cannot have two applications defining their own Gettext backend, because one of them would have to him.

A backend is equivalent to a Ecto.Repo or a Phoenix.Endpoint. If we only allowed one of them, it means your application would only every be able to talk to one database. Or listen to only one single port. Having singletons in your systems are usually a no-no.
