### ISSUE TITLE
Remove ensure_yecc_compiler

### ISSUE THREAD

**Issue by josevalim** [elixir-lang/gettext#79]
This is just a reminder for us to eventually do it. When Phoenix 1.2 is released, it will be Elixir 1.2 only and Elixir 1.2 already includes its own warning, so it should be safe to remove the task from gettext. :)

**Comment by whatyouhide** [comment]
@josevalim what ensure_yecc_compiler?

**Comment by josevalim** [comment]
My bad! :D
