### ISSUE TITLE
Add support for extracting developers comments

### ISSUE THREAD

**Issue by elfet** [elixir-lang/gettext#83]
PO files provide very helpful feature called developer comments. It will be good if gettext.extract with support it.
```elixir
gettext("Navigation") # Will be on top of page.
```

```pot
#: web/views/pages/sidebar_view.ex:100
#. "Will be on top of page."
msgid "Navigation"
msgstr ""
```

**Comment by elfet** [comment]
May be add optional argument for comments:
```elixir
gettext("Navigation", %{}, "Will be on top of page.")
```

**Comment by whatyouhide** [comment]
We definitely can't support translating actual Elixir comments to developer comments (as the `*gettext` macros work on the AST level, where the comments have already been removed).

I'm inclined to be :-1: regarding adding another argument to the `*gettext` macros, as they're already a bunch of functions with a bunch of different arities and default arguments, so I'm afraid this would make things even more complicated; however, the optional final argument is definitely a viable and pretty straightforward solution (at least to implement).

Another alternative I thought about for a while was having a `gettext_comment` macro, that could work something like this:

```elixir
gettext_comment "Will be on top of page." do
  gettext "Navigation"
end
```

I look forward to hearing ideas from the rest of the team :).

**Comment by elfet** [comment]
This is good solution!

**Comment by whatyouhide** [comment]
Since nobody else requested this feature, I'm inclined to close this as implementing this feels like it would be quite some work for what feels to be a niche feature. Can I have your blessing as well, @josevalim?

**Comment by josevalim** [comment]
@whatyouhide yes, let's close it.
