### ISSUE TITLE
Interpolation

### ISSUE THREAD

**Issue by josevalim** [elixir-lang/gettext#9]
Although gettext does not support interpolation, we could support it out of the box. The reasoning is that interpolation is common and supporting it out of the box is going to allow us to do some optimizations similar to the ones Chris did in [linguist](https://github.com/chrismccord/linguist).

The idea is that `lgettext` and `lngettext` will receive an extra argument with interpolation: a map or a list (where a list is internally converted to a map). A naïve way of supporting interpolation is this:

```elixir
def lgettext("pt", "default", "hello world %{something}", interpolation) do
  Gettext.Interpolation.interpolate("olá mundo %{something}", interpolation)
end
```

However, it would be better if we extracted all occurrence of "%{count}" or "%{whatever}" from strings during compilation time. In other words, we could compile to something like:

```elixir
def lgettext("pt", "default", "hello world %{something}", interpolation) do
  case interpolation do
    # Check all keys are in interpolation
    %{something: something} -> {:ok, "olá mundo " <> something}
    # Otherwise detect which keys are missing and return an error
    _ -> {:error, Gettext.Interpolation.missing_interpolation_keys(interpolation, [:something])
  end
end
```

Where `missing_interpolation_key` will look at the interpolation map, the required keys, and return a string saying: "missing interpolation keys: foo, bar, something".

Note though we still need to have the runtime behaviour, because the default messages need to be translated at runtime, as we never compile them. So the fallback clause still is:

```elixir
def lgettext(_locale, _context, default, interpolation) do
  case Gettext.Interpolation.interpolate(default, interpolation) do
    {:ok, interpolated} -> {:default, interpolated}
    {:error, _} = error -> error
  end
end
```

Thoughts?

**Comment by whatyouhide** [comment]
Ok, I think I got it. I'll start working on this :)

**Comment by whatyouhide** [comment]
Hey there @josevalim, quick question (I'm posting here so that others can benefit from the answer as well :smiley:).

I implemented `lgettext

**Comment by josevalim** [comment]
I would go with `lngettext(_, _, "One error", "%{count} errors", 4, %{})` which will automatically set `count: 4`.
