### ISSUE TITLE
Extraction fails when using variable domain

### ISSUE THREAD

**Issue by lboekhorst** [elixir-lang/gettext#94]
As per https://groups.google.com/forum/#!topic/elixir-lang-talk/GyYMj_4oc4o, `mix gettext.extract` crashes when used with a variable domain name, such as `dgettext(domain, "Say something")`

```
** (Protocol.UndefinedError) protocol String.Chars not implemented for {:domain, [line: 7], nil}
    (elixir) lib/string/chars.ex:3: String.Chars.impl_for!/1
    (elixir) lib/string/chars.ex:17: String.Chars.to_string/1
    lib/gettext/extractor.ex:93: Gettext.Extractor.pot_path/2
    lib/gettext/extractor.ex:89: Gettext.Extractor.create_po_struct/3
    lib/gettext/extractor.ex:83: anonymous fn/3 in Gettext.Extractor.create_po_structs_from_extracted_translations/1
    (stdlib) lists.erl:1262: :lists.foldl/3
    lib/gettext/extractor.ex:81: Gettext.Extractor.create_po_structs_from_extracted_translations/1
    lib/gettext/extractor.ex:62: Gettext.Extractor.pot_files/0
    lib/mix/tasks/gettext.extract.ex:59: Mix.Tasks.Gettext.Extract.extract/0
    lib/mix/tasks/gettext.extract.ex:30: Mix.Tasks.Gettext.Extract.run/1
    (mix) lib/mix/cli.ex:58: Mix.CLI.run_task/2
```
Preferably I would not have it crash but rather just skip over the calls it cannot extract so that I can create those myself, and fill in the calls that it did extract.

**Comment by josevalim** [comment]
@whatyouhide any ideas what we should do to solve this? Should we just silently allow variable domains or should we force them to be static (redirecting to Gettext.dgettext) if they want it to be dynamic)?

**Comment by whatyouhide** [comment]
@josevalim I'd prefer the second alternative, being stricter. It would be consistent with what we do with msg* things as well. Wdyt?

**Comment by josevalim** [comment]
Sounds like a plan! And I think our error messages already include
instructions on how to use the runtime based variants, right?

-- 


*José Valimwww.plataformatec.com.br
<http://www.plataformatec.com.br/>Founder and Director of R&D*

**Comment by whatyouhide** [comment]
Yeah, they do so it's a small and very consistent change. I'll do it in a
few hours :)

On Friday, 13 May 2016, José Valim <notifications@github.com> wrote:

> Sounds like a plan! And I think our error messages already include
> instructions on how to use the runtime based variants, right?
>
> --
>
>
> *José Valimwww.plataformatec.com.br
> <http://www.plataformatec.com.br/>Founder and Director of R&D*
>
> —
> You are receiving this because you were mentioned.
> Reply to this email directly or view it on GitHub
> <https://github.com/elixir-lang/gettext/issues/94#issuecomment-219011446>
>


-- 

Andrea Leopardi
an.leopardi@gmail.com
