### ISSUE TITLE
Wrong documentation?

### ISSUE THREAD

**Issue by maufl** [elixir-lang/gettext#95]
I think the documentation for the plural forms might contain a mistake. 
It says [here](https://github.com/elixir-lang/gettext/blob/master/lib/gettext.ex#L263) that you can configure the pluralizer in `config/config.exs` but that did not work for me. Configuring it in the custom Gettext module when using `use Gettext` does work though.

**Comment by whatyouhide** [comment]
Great catch @maufl! Thanks for reporting the issue, fixed in bb0bbfc.
